# SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsm
  namespace: opsm
  labels:
    app.kubernetes.io/name: opsm
    app.kubernetes.io/part-of: opsm
automountServiceAccountToken: false
