# SPDX-License-Identifier: MPL-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsm
  namespace: opsm
  labels:
    app.kubernetes.io/name: opsm
    app.kubernetes.io/part-of: opsm
automountServiceAccountToken: false
