# SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsm-data
  namespace: opsm
  labels:
    app.kubernetes.io/name: opsm
    app.kubernetes.io/part-of: opsm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
