// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "@std/path";
import * as Toml from "@std/toml";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as ModTs from "@proven/mod.ts";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let Env = {};

let $$Deno = {
  Env: Env
};

let Toml$1 = {};

let Path$1 = {};

let SafeUrl = {};

let Proven = {
  SafeUrl: SafeUrl
};

let defaultHttpConfig = {
  timeoutMs: 3000,
  retries: 2,
  backoffMs: 200
};

function defaultServiceConfig(port) {
  return {
    baseUrl: `http://127.0.0.1:` + port.toString(),
    token: undefined
  };
}

function exampleConfig() {
  return {
    http: defaultHttpConfig,
    claimForge: defaultServiceConfig(7001),
    checkyMonkey: defaultServiceConfig(7002),
    palimpsestLicense: defaultServiceConfig(7003),
    cicdHyperA: defaultServiceConfig(7004),
    oikos: defaultServiceConfig(7005)
  };
}

function validateServiceUrl(url, serviceName) {
  let parsed = ModTs.SafeUrl.parse(url);
  if (parsed.ok) {
    return {
      TAG: "Ok",
      _0: url
    };
  } else {
    return {
      TAG: "Error",
      _0: `Invalid URL for ` + serviceName + `: ` + url
    };
  }
}

function getIntFromJson(json, $$default) {
  let n = Core__JSON.Classify.classify(json);
  if (typeof n !== "object" || n.TAG !== "Number") {
    return $$default;
  } else {
    return n._0 | 0;
  }
}

function getStringFromJson(json) {
  let s = Core__JSON.Classify.classify(json);
  if (typeof s !== "object" || s.TAG !== "String") {
    return;
  } else {
    return s._0;
  }
}

function parseHttpConfig(raw) {
  let json = raw["http"];
  let httpRaw;
  if (json !== undefined) {
    let d = Core__JSON.Classify.classify(json);
    httpRaw = typeof d !== "object" ? ({}) : (
        d.TAG === "Object" ? d._0 : ({})
      );
  } else {
    httpRaw = {};
  }
  let v = httpRaw["timeout_ms"];
  let v$1 = httpRaw["retries"];
  let v$2 = httpRaw["backoff_ms"];
  return {
    timeoutMs: v !== undefined ? getIntFromJson(v, 3000) : 3000,
    retries: v$1 !== undefined ? getIntFromJson(v$1, 2) : 2,
    backoffMs: v$2 !== undefined ? getIntFromJson(v$2, 200) : 200
  };
}

function parseServiceConfig(raw, key, defaultPort) {
  let json = raw[key];
  let svcRaw;
  if (json !== undefined) {
    let d = Core__JSON.Classify.classify(json);
    svcRaw = typeof d !== "object" ? ({}) : (
        d.TAG === "Object" ? d._0 : ({})
      );
  } else {
    svcRaw = {};
  }
  let v = svcRaw["base_url"];
  let rawUrl = v !== undefined ? Core__Option.getOr(getStringFromJson(v), `http://127.0.0.1:` + defaultPort.toString()) : `http://127.0.0.1:` + defaultPort.toString();
  let url = validateServiceUrl(rawUrl, key);
  if (url.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: url._0
    };
  }
  let v$1 = svcRaw["token"];
  return {
    TAG: "Ok",
    _0: {
      baseUrl: url._0,
      token: v$1 !== undefined ? getStringFromJson(v$1) : undefined
    }
  };
}

async function fileExists(path) {
  try {
    await Deno.stat(path);
    return true;
  } catch (exn) {
    return false;
  }
}

async function loadConfigFrom(path) {
  try {
    let data = await Deno.readTextFile(path);
    let raw = Toml.parse(data);
    let http = parseHttpConfig(raw);
    let c = parseServiceConfig(raw, "claim_forge", 7001);
    let claimForge;
    if (c.TAG === "Ok") {
      claimForge = c._0;
    } else {
      throw Stdlib_JsError.throwWithMessage(c._0);
    }
    let c$1 = parseServiceConfig(raw, "checky_monkey", 7002);
    let checkyMonkey;
    if (c$1.TAG === "Ok") {
      checkyMonkey = c$1._0;
    } else {
      throw Stdlib_JsError.throwWithMessage(c$1._0);
    }
    let c$2 = parseServiceConfig(raw, "palimpsest_license", 7003);
    let palimpsestLicense;
    if (c$2.TAG === "Ok") {
      palimpsestLicense = c$2._0;
    } else {
      throw Stdlib_JsError.throwWithMessage(c$2._0);
    }
    let c$3 = parseServiceConfig(raw, "cicd_hyper_a", 7004);
    let cicdHyperA;
    if (c$3.TAG === "Ok") {
      cicdHyperA = c$3._0;
    } else {
      throw Stdlib_JsError.throwWithMessage(c$3._0);
    }
    let c$4 = parseServiceConfig(raw, "oikos", 7005);
    let oikos;
    if (c$4.TAG === "Ok") {
      oikos = c$4._0;
    } else {
      throw Stdlib_JsError.throwWithMessage(c$4._0);
    }
    return {
      TAG: "Ok",
      _0: {
        http: http,
        claimForge: claimForge,
        checkyMonkey: checkyMonkey,
        palimpsestLicense: palimpsestLicense,
        cicdHyperA: cicdHyperA,
        oikos: oikos
      }
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(e._1), "Failed to load config")
      };
    }
    throw e;
  }
}

async function loadConfig() {
  let envPath = Deno.env.get("OPM_CONFIG");
  if (envPath !== undefined) {
    return await loadConfigFrom(envPath);
  }
  let localPath = "opm.toml";
  let localExists = await fileExists(localPath);
  if (localExists) {
    return await loadConfigFrom(localPath);
  }
  let home = Deno.env.get("HOME");
  if (home === undefined) {
    return {
      TAG: "Error",
      _0: "opm config not found"
    };
  }
  let userPath = Path.join(home, ".config", "opm", "opm.toml");
  let userExists = await fileExists(userPath);
  if (userExists) {
    return await loadConfigFrom(userPath);
  } else {
    return {
      TAG: "Error",
      _0: "opm config not found"
    };
  }
}

async function loadConfigOrExample() {
  let config = await loadConfig();
  if (config.TAG === "Ok") {
    return config._0;
  } else {
    return exampleConfig();
  }
}

export {
  $$Deno,
  Toml$1 as Toml,
  Path$1 as Path,
  Proven,
  defaultHttpConfig,
  defaultServiceConfig,
  exampleConfig,
  validateServiceUrl,
  getIntFromJson,
  getStringFromJson,
  parseHttpConfig,
  parseServiceConfig,
  fileExists,
  loadConfigFrom,
  loadConfig,
  loadConfigOrExample,
}
/* @std/path Not a pure module */
