// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as ModTs from "@proven/mod.ts";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let $$Deno = {};

let SafeJson = {};

let Proven = {
  SafeJson: SafeJson
};

function sleep(ms) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve(), ms);
  });
}

function buildUrl(baseUrl, path) {
  let trimmedBase = baseUrl.replace(/\/+$/, "");
  return trimmedBase + path;
}

async function postJson(baseUrl, path, token, body, opts) {
  let url = buildUrl(baseUrl, path);
  let attempts = opts.retries + 1 | 0;
  let headers = {};
  headers["Content-Type"] = "application/json";
  if (token !== undefined) {
    headers["Authorization"] = `Bearer ` + token;
  }
  let lastError = "Request failed";
  let success = false;
  for (let attempt = 0; attempt < attempts; ++attempt) {
    if (!success) {
      try {
        let controller = new AbortController();
        let timeoutId = setTimeout(() => {
          controller.abort();
        }, opts.timeoutMs);
        let response = await fetch(url, {
          method: "POST",
          headers: headers,
          body: body,
          signal: controller.signal
        });
        clearTimeout(timeoutId);
        if (response.ok) {
          success = true;
        } else {
          lastError = `HTTP error: ` + response.status.toString() + ` ` + response.statusText;
          if ((attempt + 1 | 0) < attempts) {
            await sleep(opts.backoffMs * (attempt + 1 | 0) | 0);
          }
        }
      } catch (raw_e) {
        let e = Primitive_exceptions.internalToException(raw_e);
        if (e.RE_EXN_ID === "JsExn") {
          lastError = Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error");
          if ((attempt + 1 | 0) < attempts) {
            await sleep(opts.backoffMs * (attempt + 1 | 0) | 0);
          }
        } else {
          throw e;
        }
      }
    }
  }
  if (success) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: lastError
    };
  }
}

async function getJson(baseUrl, path, token, opts) {
  let url = buildUrl(baseUrl, path);
  let attempts = opts.retries + 1 | 0;
  let headers = {};
  headers["Accept"] = "application/json";
  if (token !== undefined) {
    headers["Authorization"] = `Bearer ` + token;
  }
  let lastError = "Request failed";
  let result;
  for (let attempt = 0; attempt < attempts; ++attempt) {
    if (Core__Option.isNone(result)) {
      try {
        let controller = new AbortController();
        let timeoutId = setTimeout(() => {
          controller.abort();
        }, opts.timeoutMs);
        let response = await fetch(url, {
          method: "GET",
          headers: headers,
          signal: controller.signal
        });
        clearTimeout(timeoutId);
        if (response.ok) {
          let text = await response.text();
          let parsed = ModTs.SafeJson.parse(text);
          if (parsed.ok) {
            let v = parsed.value;
            result = v !== undefined ? ({
                TAG: "Ok",
                _0: v
              }) : ({
                TAG: "Error",
                _0: "JSON parse returned null"
              });
          } else {
            result = {
              TAG: "Error",
              _0: `JSON parse error: ` + Core__Option.getOr(parsed.error, "unknown")
            };
          }
        } else {
          lastError = `HTTP error: ` + response.status.toString() + ` ` + response.statusText;
          if ((attempt + 1 | 0) < attempts) {
            await sleep(opts.backoffMs * (attempt + 1 | 0) | 0);
          }
        }
      } catch (raw_e) {
        let e = Primitive_exceptions.internalToException(raw_e);
        if (e.RE_EXN_ID === "JsExn") {
          lastError = Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error");
          if ((attempt + 1 | 0) < attempts) {
            await sleep(opts.backoffMs * (attempt + 1 | 0) | 0);
          }
        } else {
          throw e;
        }
      }
    }
  }
  let r = result;
  if (r !== undefined) {
    return r;
  } else {
    return {
      TAG: "Error",
      _0: lastError
    };
  }
}

export {
  $$Deno,
  Proven,
  sleep,
  buildUrl,
  postJson,
  getJson,
}
/* Stdlib_JsExn Not a pure module */
