// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.res.js";
import * as Wiring from "./Wiring.res.js";

let $$Deno = {};

function printHelp() {
  console.log("opsm - Odds-and-sods Package Manager");
  console.log("");
  console.log("USAGE:");
  console.log("  opsm <command> [options]");
  console.log("");
  console.log("COMMANDS:");
  console.log("  publish <path>    Publish a package through the trust pipeline");
  console.log("  audit <package>   Audit a package for sustainability and compliance");
  console.log("  status            Show service status and configuration");
  console.log("  help              Show this help message");
  console.log("");
  console.log("CONFIGURATION:");
  console.log("  Config file search order:");
  console.log("  1. $OPSM_CONFIG environment variable");
  console.log("  2. ./opsm.toml (local directory)");
  console.log("  3. ~/.config/opsm/opsm.toml (user config)");
  console.log("");
  console.log("EXAMPLES:");
  console.log("  opsm publish ./my-package");
  console.log("  opsm audit @scope/package");
  console.log("  opsm status");
}

function printVersion() {
  console.log("opsm 0.1.0");
}

function parseArgs(args) {
  let cmd = args[0];
  if (cmd === undefined) {
    return "Help";
  }
  switch (cmd) {
    case "audit" :
      let pkg = args[1];
      if (pkg !== undefined) {
        return {
          TAG: "Audit",
          _0: pkg
        };
      } else {
        console.error("Error: audit requires a package argument");
        return "Help";
      }
    case "--help" :
    case "-h" :
    case "help" :
      return "Help";
    case "publish" :
      let path = args[1];
      if (path !== undefined) {
        return {
          TAG: "Publish",
          _0: path
        };
      } else {
        console.error("Error: publish requires a path argument");
        return "Help";
      }
    case "status" :
      return "Status";
    case "--version" :
    case "-v" :
    case "version" :
      return "Version";
    default:
      return {
        TAG: "Unknown",
        _0: cmd
      };
  }
}

async function main() {
  let args = Deno.args;
  let command = parseArgs(args);
  if (typeof command !== "object") {
    switch (command) {
      case "Status" :
        let config = await Config.loadConfigOrExample();
        let e = await Wiring.runStatus(config);
        if (e.TAG === "Ok") {
          Deno.exit(0);
          return;
        }
        console.error(`Status check failed: ` + e._0);
        Deno.exit(1);
        return;
      case "Help" :
        printHelp();
        Deno.exit(0);
        return;
      case "Version" :
        console.log("opsm 0.1.0");
        Deno.exit(0);
        return;
    }
  } else {
    switch (command.TAG) {
      case "Publish" :
        let config$1 = await Config.loadConfigOrExample();
        let e$1 = await Wiring.runPublish(config$1, command._0);
        if (e$1.TAG === "Ok") {
          Deno.exit(0);
          return;
        }
        console.error(`Publish failed: ` + e$1._0);
        Deno.exit(1);
        return;
      case "Audit" :
        let config$2 = await Config.loadConfigOrExample();
        let e$2 = await Wiring.runAudit(config$2, command._0);
        if (e$2.TAG === "Ok") {
          Deno.exit(0);
          return;
        }
        console.error(`Audit failed: ` + e$2._0);
        Deno.exit(1);
        return;
      case "Unknown" :
        console.error(`Unknown command: ` + command._0);
        console.error("Run 'opsm help' for usage information");
        Deno.exit(1);
        return;
    }
  }
}

main();

export {
  $$Deno,
  printHelp,
  printVersion,
  parseArgs,
  main,
}
/*  Not a pure module */
