// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Oikos from "./clients/Oikos.res.js";
import * as Palimpsest from "./clients/Palimpsest.res.js";
import * as CheckyMonkey from "./clients/CheckyMonkey.res.js";

async function runPublish(config, path) {
  let httpOpts_timeoutMs = config.http.timeoutMs;
  let httpOpts_retries = config.http.retries;
  let httpOpts_backoffMs = config.http.backoffMs;
  let httpOpts = {
    timeoutMs: httpOpts_timeoutMs,
    retries: httpOpts_retries,
    backoffMs: httpOpts_backoffMs
  };
  console.log(`Publishing package from: ` + path);
  console.log("  → Checking license compliance via palimpsest-license...");
  let palimpsestClient = Palimpsest.make(config.palimpsestLicense.baseUrl, config.palimpsestLicense.token, httpOpts);
  let licenseResult = await Palimpsest.analyze(palimpsestClient, {
    artifactPath: path,
    includeTransitive: true,
    targetLicense: "PMPL-1.0"
  });
  if (licenseResult.TAG === "Ok") {
    if (licenseResult._0.compatibility.compatible) {
      console.log("  ✓ License compatible");
    } else {
      console.log("  ✗ License conflicts detected");
    }
  } else {
    console.log(`  ✗ License check failed: ` + licenseResult._0);
  }
  console.log("  → Running verification via checky-monkey...");
  let checkyClient = CheckyMonkey.make(config.checkyMonkey.baseUrl, config.checkyMonkey.token, httpOpts);
  let verifyResult = await CheckyMonkey.submitVerification(checkyClient, {
    repositoryUrl: path,
    commitSha: "HEAD",
    verificationTypes: [
      "PropertyTests",
      "TypeChecking"
    ],
    timeout: 300
  });
  if (verifyResult.TAG === "Ok") {
    console.log(`  ✓ Verification submitted: ` + verifyResult._0.requestId);
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  let e = verifyResult._0;
  console.log(`  ✗ Verification failed: ` + e);
  return {
    TAG: "Error",
    _0: e
  };
}

async function runAudit(config, packageName) {
  let httpOpts_timeoutMs = config.http.timeoutMs;
  let httpOpts_retries = config.http.retries;
  let httpOpts_backoffMs = config.http.backoffMs;
  let httpOpts = {
    timeoutMs: httpOpts_timeoutMs,
    retries: httpOpts_retries,
    backoffMs: httpOpts_backoffMs
  };
  console.log(`Auditing package: ` + packageName);
  console.log("  → Getting sustainability scores from oikos...");
  let oikosClient = Oikos.make(config.oikos.baseUrl, config.oikos.token, httpOpts);
  let analysisResult = await Oikos.analyzeRepository(oikosClient, {
    repositoryUrl: packageName,
    branch: undefined,
    commitSha: undefined
  });
  if (analysisResult.TAG === "Ok") {
    let resp = analysisResult._0;
    console.log(`  ✓ Overall score: ` + resp.overallScore.toString() + `/100`);
    console.log(`    - Maintainability: ` + resp.scores.maintainability.toString());
    console.log(`    - Documentation: ` + resp.scores.documentation.toString());
    console.log(`    - Test Coverage: ` + resp.scores.testCoverage.toString());
    console.log(`    - Security: ` + resp.scores.securityPosture.toString());
  } else {
    console.log(`  ✗ Analysis failed: ` + analysisResult._0);
  }
  console.log("  → Checking licenses via palimpsest-license...");
  let palimpsestClient = Palimpsest.make(config.palimpsestLicense.baseUrl, config.palimpsestLicense.token, httpOpts);
  let licenseResult = await Palimpsest.analyze(palimpsestClient, {
    artifactPath: packageName,
    includeTransitive: true,
    targetLicense: undefined
  });
  if (licenseResult.TAG === "Ok") {
    let count = licenseResult._0.detectedLicenses.length;
    console.log(`  ✓ Found ` + count.toString() + ` licenses`);
  } else {
    console.log(`  ✗ License analysis failed: ` + licenseResult._0);
  }
  return {
    TAG: "Ok",
    _0: undefined
  };
}

async function runStatus(config) {
  let httpOpts_timeoutMs = config.http.timeoutMs;
  let httpOpts_retries = config.http.retries;
  let httpOpts_backoffMs = config.http.backoffMs;
  let httpOpts = {
    timeoutMs: httpOpts_timeoutMs,
    retries: httpOpts_retries,
    backoffMs: httpOpts_backoffMs
  };
  console.log("OPSM Service Status");
  console.log("==================");
  let oikosClient = Oikos.make(config.oikos.baseUrl, config.oikos.token, httpOpts);
  let oikosHealth = await Oikos.health(oikosClient);
  if (oikosHealth.TAG === "Ok") {
    let h = oikosHealth._0;
    let match = h.status;
    let status;
    switch (match) {
      case "Healthy" :
        status = "✓ healthy";
        break;
      case "Degraded" :
        status = "⚠ degraded";
        break;
      case "Unhealthy" :
        status = "✗ unhealthy";
        break;
    }
    console.log(`oikos: ` + status + ` (` + h.version + `)`);
  } else {
    console.log("oikos: ✗ unreachable");
  }
  let checkyClient = CheckyMonkey.make(config.checkyMonkey.baseUrl, config.checkyMonkey.token, httpOpts);
  let checkyHealth = await CheckyMonkey.health(checkyClient);
  if (checkyHealth.TAG === "Ok") {
    let h$1 = checkyHealth._0;
    let match$1 = h$1.status;
    let status$1;
    switch (match$1) {
      case "Healthy" :
        status$1 = "✓ healthy";
        break;
      case "Degraded" :
        status$1 = "⚠ degraded";
        break;
      case "Unhealthy" :
        status$1 = "✗ unhealthy";
        break;
    }
    console.log(`checky-monkey: ` + status$1 + ` (` + h$1.version + `)`);
  } else {
    console.log("checky-monkey: ✗ unreachable");
  }
  console.log("");
  console.log("Configuration");
  console.log("-------------");
  console.log(`checky-monkey: ` + config.checkyMonkey.baseUrl);
  console.log(`palimpsest-license: ` + config.palimpsestLicense.baseUrl);
  console.log(`oikos: ` + config.oikos.baseUrl);
  return {
    TAG: "Ok",
    _0: undefined
  };
}

export {
  runPublish,
  runAudit,
  runStatus,
}
/* Oikos Not a pure module */
