// GENERATED BY v-graphql-gen - DO NOT EDIT
module api

import v_ecosystem.v_api_interfaces.v_graphql

pub interface AerieGraphQLService {
	telemetry_snapshot() string
	route_forensics_snapshot(target string) string
	audit_snapshot(limit int) string
}
