// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.js";

function make(baseUrl, token, opts) {
  return {
    baseUrl: baseUrl,
    token: token,
    opts: opts
  };
}

function encodeVerificationType(t) {
  switch (t) {
    case "PropertyTests" :
      return "property-tests";
    case "FuzzTesting" :
      return "fuzz-testing";
    case "TypeChecking" :
      return "type-checking";
    case "FormalVerification" :
      return "formal-verification";
    case "MutationTesting" :
      return "mutation-testing";
  }
}

function decodeVerificationType(s) {
  switch (s) {
    case "formal-verification" :
      return "FormalVerification";
    case "fuzz-testing" :
      return "FuzzTesting";
    case "mutation-testing" :
      return "MutationTesting";
    case "type-checking" :
      return "TypeChecking";
    default:
      return "PropertyTests";
  }
}

function encodeVerificationRequest(req) {
  let obj = {};
  obj["repositoryUrl"] = req.repositoryUrl;
  obj["commitSha"] = req.commitSha;
  obj["verificationTypes"] = req.verificationTypes.map(encodeVerificationType);
  let t = req.timeout;
  if (t !== undefined) {
    obj["timeout"] = t;
  }
  return JSON.stringify(obj);
}

function decodeVerificationStatus(s) {
  switch (s) {
    case "completed" :
      return "Completed";
    case "queued" :
      return "Queued";
    case "running" :
      return "Running";
    default:
      return "Failed";
  }
}

async function submitVerification(client, request) {
  let body = encodeVerificationRequest(request);
  let e = await Http.postJson(client.baseUrl, "/verify", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let sha = encodeURIComponent(request.commitSha);
  let e$1 = await Http.getJson(client.baseUrl, `/verify/status/` + sha, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        requestId: sha,
        status: "Queued",
        startedAt: undefined,
        completedAt: undefined,
        results: undefined
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function getStatus(client, requestId) {
  let path = `/verify/` + encodeURIComponent(requestId);
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        requestId: requestId,
        status: "Queued",
        startedAt: undefined,
        completedAt: undefined,
        results: undefined
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function listVerificationTypes(client) {
  let e = await Http.getJson(client.baseUrl, "/verification-types", client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: [
        "PropertyTests",
        "FuzzTesting",
        "TypeChecking",
        "FormalVerification",
        "MutationTesting"
      ]
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function cancel(client, requestId) {
  let path = `/verify/` + encodeURIComponent(requestId) + `/cancel`;
  let e = await Http.postJson(client.baseUrl, path, client.token, "{}", client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function health(client) {
  let e = await Http.getJson(client.baseUrl, "/health", client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        status: "Healthy",
        version: "unknown",
        activeJobs: 0,
        queueLength: 0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

export {
  make,
  encodeVerificationType,
  decodeVerificationType,
  encodeVerificationRequest,
  decodeVerificationStatus,
  submitVerification,
  getStatus,
  listVerificationTypes,
  cancel,
  health,
}
/* Http Not a pure module */
