// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function make(baseUrl, token, opts) {
  return {
    baseUrl: baseUrl,
    token: token,
    opts: opts
  };
}

function encodeAttestationType(t) {
  switch (t) {
    case "ClaimForge" :
      return "claim-forge";
    case "Sigstore" :
      return "sigstore";
    case "InToto" :
      return "in-toto";
  }
}

function encodeAttestationRef(ref) {
  let obj = {};
  obj["type"] = encodeAttestationType(ref.attestationType);
  obj["uri"] = ref.uri;
  obj["digest"] = ref.digest;
  return obj;
}

function encodePackageMetadata(m) {
  let obj = {};
  obj["name"] = m.name;
  obj["version"] = m.version;
  let d = m.description;
  if (d !== undefined) {
    obj["description"] = d;
  }
  obj["license"] = m.license;
  let r = m.repository;
  if (r !== undefined) {
    obj["repository"] = r;
  }
  obj["authors"] = m.authors.map(prim => prim);
  obj["keywords"] = m.keywords.map(prim => prim);
  return obj;
}

function encodePublishRequest(req) {
  let obj = {};
  obj["manifest"] = encodePackageMetadata(req.manifest);
  let url = req.tarballUrl;
  if (url !== undefined) {
    obj["tarballUrl"] = url;
  }
  obj["attestations"] = req.attestations.map(encodeAttestationRef);
  return JSON.stringify(obj);
}

function encodeQueryRequest(req) {
  let v = req.version;
  let versionPart = v !== undefined ? `/` + v : "";
  let match = req.includeScores;
  let queryParams = match !== undefined && match ? "?includeScores=true" : "";
  return encodeURIComponent(req.name) + versionPart + queryParams;
}

async function publish(client, request) {
  let body = encodePublishRequest(request);
  let e = await Http.postJson(client.baseUrl, "/packages/publish", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let name = encodeURIComponent(request.manifest.name);
  let version = request.manifest.version;
  let e$1 = await Http.getJson(client.baseUrl, `/packages/` + name + `/` + version, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        packageId: request.manifest.name + `@` + request.manifest.version,
        version: request.manifest.version,
        publishedAt: "",
        registryUrl: client.baseUrl + `/packages/` + name + `/` + version,
        federationStatus: {
          github: {
            synced: false,
            lastSync: undefined,
            error: undefined
          },
          gitlab: {
            synced: false,
            lastSync: undefined,
            error: undefined
          },
          codeberg: {
            synced: false,
            lastSync: undefined,
            error: undefined
          },
          radicle: {
            synced: false,
            lastSync: undefined,
            error: undefined
          },
          ipfs: undefined
        }
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function queryPackage(client, request) {
  let path = `/packages/` + encodeQueryRequest(request);
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        package: {
          name: request.name,
          version: Core__Option.getOr(request.version, "0.0.0"),
          description: undefined,
          license: "PMPL-1.0",
          repository: undefined,
          authors: [],
          keywords: [],
          dependencies: {},
          devDependencies: undefined
        },
        versions: [],
        latestVersion: "0.0.0",
        scores: undefined,
        dependents: 0,
        downloads: 0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function listRulesets(client) {
  let e = await Http.getJson(client.baseUrl, "/rulesets", client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: []
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function getRuleset(client, rulesetId) {
  let path = `/rulesets/` + encodeURIComponent(rulesetId);
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        id: rulesetId,
        name: "",
        version: "0.0.0",
        rules: [],
        appliesTo: []
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function validateManifest(client, manifest, rulesetIds) {
  let obj = {};
  obj["manifest"] = encodePackageMetadata(manifest);
  obj["rulesetIds"] = Core__Option.getOr(rulesetIds, ["default"]).map(prim => prim);
  let body = JSON.stringify(obj);
  let e = await Http.postJson(client.baseUrl, "/validate", client.token, body, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        valid: true,
        errors: [],
        warnings: []
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function getFederationStatus(client, packageName, version) {
  let path = `/packages/` + encodeURIComponent(packageName) + `/` + version + `/federation`;
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        packageName: packageName,
        version: version,
        syncedAt: "",
        targets: {}
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

export {
  make,
  encodeAttestationType,
  encodeAttestationRef,
  encodePackageMetadata,
  encodePublishRequest,
  encodeQueryRequest,
  publish,
  queryPackage,
  listRulesets,
  getRuleset,
  validateManifest,
  getFederationStatus,
}
/* Http Not a pure module */
