// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function make(baseUrl, token, opts) {
  return {
    baseUrl: baseUrl,
    token: token,
    opts: opts
  };
}

let DenoCommand = {};

let TextDecoder = {};

function encodeClaimType(t) {
  switch (t) {
    case "BuildProvenance" :
      return "build-provenance";
    case "SourceAttestation" :
      return "source-attestation";
    case "VulnerabilityScan" :
      return "vulnerability-scan";
    case "LicenseCompliance" :
      return "license-compliance";
    case "CodeReview" :
      return "code-review";
  }
}

function decodeClaimType(s) {
  switch (s) {
    case "code-review" :
      return "CodeReview";
    case "license-compliance" :
      return "LicenseCompliance";
    case "source-attestation" :
      return "SourceAttestation";
    case "vulnerability-scan" :
      return "VulnerabilityScan";
    default:
      return "BuildProvenance";
  }
}

function encodeAttestRequest(req) {
  let obj = {};
  obj["artifactPath"] = req.artifactPath;
  obj["artifactDigest"] = req.artifactDigest;
  obj["claimType"] = encodeClaimType(req.claimType);
  let m = req.metadata;
  if (m !== undefined) {
    obj["metadata"] = m;
  }
  return JSON.stringify(obj);
}

function encodeVerifyRequest(req) {
  let obj = {};
  obj["attestationUri"] = req.attestationUri;
  obj["artifactDigest"] = req.artifactDigest;
  return JSON.stringify(obj);
}

async function attest(client, request) {
  let body = encodeAttestRequest(request);
  let e = await Http.postJson(client.baseUrl, "/attest", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let digest = encodeURIComponent(request.artifactDigest);
  let e$1 = await Http.getJson(client.baseUrl, `/attestations/` + digest, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        attestationId: "",
        claimType: request.claimType,
        createdAt: "",
        expiresAt: undefined,
        attestationUri: "",
        signature: "",
        publicKeyId: ""
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function verify(client, request) {
  let body = encodeVerifyRequest(request);
  let e = await Http.postJson(client.baseUrl, "/verify", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let uri = encodeURIComponent(request.attestationUri);
  let e$1 = await Http.getJson(client.baseUrl, `/verify/` + uri, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        valid: true,
        claimType: "BuildProvenance",
        issuer: "",
        issuedAt: "",
        errors: undefined
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function listClaimTypes(client) {
  let e = await Http.getJson(client.baseUrl, "/claim-types", client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: [
        "BuildProvenance",
        "SourceAttestation",
        "VulnerabilityScan",
        "LicenseCompliance",
        "CodeReview"
      ]
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function getAttestation(client, attestationId) {
  let path = `/attestations/` + encodeURIComponent(attestationId);
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        attestationId: attestationId,
        claimType: "BuildProvenance",
        createdAt: "",
        expiresAt: undefined,
        attestationUri: "",
        signature: "",
        publicKeyId: ""
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

function makeCli(binaryPathOpt) {
  let binaryPath = binaryPathOpt !== undefined ? binaryPathOpt : "claim-forge";
  return {
    binaryPath: binaryPath
  };
}

async function cliAttest(cli, artifactPath, claimType, outputPath) {
  let args = [
    "attest",
    "--type",
    encodeClaimType(claimType),
    "--artifact",
    artifactPath
  ];
  let args$1 = outputPath !== undefined ? args.concat([
      "--output",
      outputPath
    ]) : args;
  try {
    let cmd = new (Deno.Command)(cli.binaryPath, {
      args: args$1,
      stdout: "piped",
      stderr: "piped"
    });
    let output = await cmd.output();
    let decoder = new TextDecoder();
    if (output.code !== 0) {
      let errorText = decoder.decode(output.stderr);
      return {
        TAG: "Error",
        _0: `claim-forge failed: ` + errorText
      };
    }
    let outputText = decoder.decode(output.stdout);
    return {
      TAG: "Ok",
      _0: outputText.trim()
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error")
      };
    }
    throw e;
  }
}

async function cliVerify(cli, attestationPath, artifactPath) {
  let args = [
    "verify",
    "--attestation",
    attestationPath,
    "--artifact",
    artifactPath
  ];
  try {
    let cmd = new (Deno.Command)(cli.binaryPath, {
      args: args,
      stdout: "piped",
      stderr: "piped"
    });
    let output = await cmd.output();
    let decoder = new TextDecoder();
    if (output.code === 0) {
      return {
        TAG: "Ok",
        _0: true
      };
    }
    let errorText = decoder.decode(output.stderr);
    return {
      TAG: "Error",
      _0: `verification failed: ` + errorText
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error")
      };
    }
    throw e;
  }
}

export {
  make,
  DenoCommand,
  TextDecoder,
  encodeClaimType,
  decodeClaimType,
  encodeAttestRequest,
  encodeVerifyRequest,
  attest,
  verify,
  listClaimTypes,
  getAttestation,
  makeCli,
  cliAttest,
  cliVerify,
}
/* Http Not a pure module */
