// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function make(baseUrl, token, opts) {
  return {
    baseUrl: baseUrl,
    token: token,
    opts: opts
  };
}

function encodeAnalysisRequest(req) {
  let obj = {};
  obj["repositoryUrl"] = req.repositoryUrl;
  let b = req.branch;
  if (b !== undefined) {
    obj["branch"] = b;
  }
  let s = req.commitSha;
  if (s !== undefined) {
    obj["commitSha"] = s;
  }
  return JSON.stringify(obj);
}

function encodeDiffRequest(req) {
  let obj = {};
  obj["repositoryUrl"] = req.repositoryUrl;
  obj["baseRef"] = req.baseRef;
  obj["headRef"] = req.headRef;
  return JSON.stringify(obj);
}

function decodeString(json, key) {
  let d = Core__JSON.Classify.classify(json);
  if (typeof d !== "object") {
    return;
  }
  if (d.TAG !== "Object") {
    return;
  }
  let v = d._0[key];
  if (v === undefined) {
    return;
  }
  let s = Core__JSON.Classify.classify(v);
  if (typeof s !== "object" || s.TAG !== "String") {
    return;
  } else {
    return s._0;
  }
}

function decodeInt(json, key) {
  let d = Core__JSON.Classify.classify(json);
  if (typeof d !== "object") {
    return;
  }
  if (d.TAG !== "Object") {
    return;
  }
  let v = d._0[key];
  if (v === undefined) {
    return;
  }
  let n = Core__JSON.Classify.classify(v);
  if (typeof n !== "object" || n.TAG !== "Number") {
    return;
  } else {
    return n._0 | 0;
  }
}

function decodeSeverity(s) {
  switch (s) {
    case "critical" :
      return "Critical";
    case "high" :
      return "High";
    case "medium" :
      return "Medium";
    default:
      return "Low";
  }
}

function decodeServiceStatus(s) {
  switch (s) {
    case "degraded" :
      return "Degraded";
    case "healthy" :
      return "Healthy";
    default:
      return "Unhealthy";
  }
}

function decodeScores(json) {
  return {
    maintainability: Core__Option.getOr(decodeInt(json, "maintainability"), 0),
    documentation: Core__Option.getOr(decodeInt(json, "documentation"), 0),
    testCoverage: Core__Option.getOr(decodeInt(json, "testCoverage"), 0),
    communityHealth: Core__Option.getOr(decodeInt(json, "communityHealth"), 0),
    securityPosture: Core__Option.getOr(decodeInt(json, "securityPosture"), 0),
    dependencyHealth: Core__Option.getOr(decodeInt(json, "dependencyHealth"), 0),
    releaseMaturity: Core__Option.getOr(decodeInt(json, "releaseMaturity"), 0),
    codeQuality: Core__Option.getOr(decodeInt(json, "codeQuality"), 0)
  };
}

function decodeAnalysisResponse(json) {
  let d = Core__JSON.Classify.classify(json);
  if (typeof d !== "object") {
    return {
      TAG: "Error",
      _0: "Invalid response format"
    };
  }
  if (d.TAG !== "Object") {
    return {
      TAG: "Error",
      _0: "Invalid response format"
    };
  }
  let s = d._0["scores"];
  return {
    TAG: "Ok",
    _0: {
      repositoryUrl: Core__Option.getOr(decodeString(json, "repositoryUrl"), ""),
      analyzedAt: Core__Option.getOr(decodeString(json, "analyzedAt"), ""),
      overallScore: Core__Option.getOr(decodeInt(json, "overallScore"), 0),
      scores: s !== undefined ? decodeScores(s) : ({
          maintainability: 0,
          documentation: 0,
          testCoverage: 0,
          communityHealth: 0,
          securityPosture: 0,
          dependencyHealth: 0,
          releaseMaturity: 0,
          codeQuality: 0
        }),
      recommendations: [],
      risks: []
    }
  };
}

function decodeHealthResponse(json) {
  return {
    TAG: "Ok",
    _0: {
      status: decodeServiceStatus(Core__Option.getOr(decodeString(json, "status"), "unhealthy")),
      version: Core__Option.getOr(decodeString(json, "version"), "unknown"),
      uptime: Core__Option.getOr(decodeInt(json, "uptime"), 0)
    }
  };
}

async function analyzeRepository(client, request) {
  let body = encodeAnalysisRequest(request);
  let e = await Http.postJson(client.baseUrl, "/analysis/repository", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let encodedUrl = encodeURIComponent(request.repositoryUrl);
  let e$1 = await Http.getJson(client.baseUrl, `/analysis/repository/` + encodedUrl, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return decodeAnalysisResponse(e$1._0);
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function analyzeDiff(client, request) {
  let body = encodeDiffRequest(request);
  let e = await Http.postJson(client.baseUrl, "/analysis/diff", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let encodedUrl = encodeURIComponent(request.repositoryUrl);
  await Http.getJson(client.baseUrl, `/analysis/diff/` + encodedUrl, client.token, client.opts);
  return {
    TAG: "Ok",
    _0: {
      repositoryUrl: request.repositoryUrl,
      baseRef: request.baseRef,
      headRef: request.headRef,
      analyzedAt: "",
      overallDelta: 0,
      impactSummary: ""
    }
  };
}

async function health(client) {
  let e = await Http.getJson(client.baseUrl, "/health", client.token, client.opts);
  if (e.TAG === "Ok") {
    return decodeHealthResponse(e._0);
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

export {
  make,
  encodeAnalysisRequest,
  encodeDiffRequest,
  decodeString,
  decodeInt,
  decodeSeverity,
  decodeServiceStatus,
  decodeScores,
  decodeAnalysisResponse,
  decodeHealthResponse,
  analyzeRepository,
  analyzeDiff,
  health,
}
/* Http Not a pure module */
