// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function make(baseUrl, token, opts) {
  return {
    baseUrl: baseUrl,
    token: token,
    opts: opts
  };
}

let DenoCommand = {};

let TextDecoder = {};

function encodeAnalyzeRequest(req) {
  let obj = {};
  obj["artifactPath"] = req.artifactPath;
  let b = req.includeTransitive;
  if (b !== undefined) {
    obj["includeTransitive"] = b;
  }
  let l = req.targetLicense;
  if (l !== undefined) {
    obj["targetLicense"] = l;
  }
  return JSON.stringify(obj);
}

function encodeCompatibilityRequest(license1, license2) {
  let obj = {};
  obj["license1"] = license1;
  obj["license2"] = license2;
  return JSON.stringify(obj);
}

async function analyze(client, request) {
  let body = encodeAnalyzeRequest(request);
  let e = await Http.postJson(client.baseUrl, "/analyze", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let encodedPath = encodeURIComponent(request.artifactPath);
  let e$1 = await Http.getJson(client.baseUrl, `/analyze/` + encodedPath, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        analyzedAt: "",
        detectedLicenses: [],
        compatibility: {
          compatible: true,
          targetLicense: request.targetLicense,
          conflicts: []
        },
        obligations: [],
        risks: []
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function checkCompatibility(client, license1, license2) {
  let body = encodeCompatibilityRequest(license1, license2);
  let e = await Http.postJson(client.baseUrl, "/compatibility", client.token, body, client.opts);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let l1 = encodeURIComponent(license1);
  let l2 = encodeURIComponent(license2);
  let e$1 = await Http.getJson(client.baseUrl, `/compatibility/` + l1 + `/` + l2, client.token, client.opts);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        license1: license1,
        license2: license2,
        compatible: true,
        direction: "Both",
        reason: undefined
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
}

async function getLicenseInfo(client, spdxId) {
  let path = `/licenses/` + encodeURIComponent(spdxId);
  let e = await Http.getJson(client.baseUrl, path, client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        spdxId: spdxId,
        name: "",
        url: "",
        osiApproved: false,
        fsfLibre: false,
        copyleft: false,
        copyleftStrength: undefined,
        permissions: [],
        conditions: [],
        limitations: []
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

async function listLicenses(client) {
  let e = await Http.getJson(client.baseUrl, "/licenses", client.token, client.opts);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: []
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

function makeCli(binaryPathOpt) {
  let binaryPath = binaryPathOpt !== undefined ? binaryPathOpt : "palimpsest-license";
  return {
    binaryPath: binaryPath
  };
}

async function cliAnalyze(cli, artifactPath, includeTransitive) {
  let args = [
    "analyze",
    artifactPath
  ];
  let args$1 = includeTransitive ? args.concat(["--transitive"]) : args;
  try {
    let cmd = new (Deno.Command)(cli.binaryPath, {
      args: args$1,
      stdout: "piped",
      stderr: "piped"
    });
    let output = await cmd.output();
    let decoder = new TextDecoder();
    if (output.code !== 0) {
      let errorText = decoder.decode(output.stderr);
      return {
        TAG: "Error",
        _0: `palimpsest-license failed: ` + errorText
      };
    }
    let outputText = decoder.decode(output.stdout);
    return {
      TAG: "Ok",
      _0: outputText
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error")
      };
    }
    throw e;
  }
}

async function cliCheckCompatibility(cli, license1, license2) {
  let args = [
    "check",
    license1,
    license2
  ];
  try {
    let cmd = new (Deno.Command)(cli.binaryPath, {
      args: args,
      stdout: "piped",
      stderr: "piped"
    });
    let output = await cmd.output();
    let decoder = new TextDecoder();
    if (output.code === 0) {
      return {
        TAG: "Ok",
        _0: true
      };
    }
    let errorText = decoder.decode(output.stderr);
    return {
      TAG: "Error",
      _0: `compatibility check failed: ` + errorText
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(e._1), "Unknown error")
      };
    }
    throw e;
  }
}

export {
  make,
  DenoCommand,
  TextDecoder,
  encodeAnalyzeRequest,
  encodeCompatibilityRequest,
  analyze,
  checkCompatibility,
  getLicenseInfo,
  listLicenses,
  makeCli,
  cliAnalyze,
  cliCheckCompatibility,
}
/* Http Not a pure module */
