// GENERATED BY v-grpc-gen - DO NOT EDIT
module api

import v_ecosystem.v_grpc

pub interface AerieService {
	get_telemetry_snapshot(req TelemetryRequest) TelemetryPayload
	get_route_forensics_snapshot(req RouteForensicsRequest) RouteForensicsPayload
	get_audit_snapshot(req AuditRequest) AuditPayload
}

// --- High-Assurance Provider ---
pub struct AerieProvider {
mut:
	// Points to the Zig FFI / Idris ABI handle
	abi_handle voidptr
}
